# Generated by Django 5.1.11 on 2026-06-22 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'indexes': [models.Index(fields=['-updated_at', '-id'], name='products_pr_updated_226cf2_idx'), models.Index(fields=['category', '-updated_at', '-id'], name='products_pr_categor_fbaabf_idx')],
            },
        ),
    ]
