# Generated by Django 5.1.11 on 2026-06-22 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_created_at_alter_product_updated_at'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='product',
            name='products_pr_updated_226cf2_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='products_pr_categor_fbaabf_idx',
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['-created_at', '-id'], name='products_pr_created_e6f9fc_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category', '-created_at', '-id'], name='products_pr_categor_9a7517_idx'),
        ),
    ]
